### ISSUE TITLE
Errors...

### ISSUE THREAD

**Issue by TehSebaXx** [martincarrera/clash-royale-api#33]
Running `mongod` i get the following error:

```D:\Dev\Git\clash-royale-api>mongod
2017-02-16T20:40:27.060+0100 I CONTROL  [initandlisten] MongoDB starting : pid=6292 port=27017 dbpath=D:\data\db\ 64-bit host=S3BAX-PC
2017-02-16T20:40:27.061+0100 I CONTROL  [initandlisten] targetMinOS: Windows 7/Windows Server 2008 R2
2017-02-16T20:40:27.062+0100 I CONTROL  [initandlisten] db version v3.4.2
2017-02-16T20:40:27.062+0100 I CONTROL  [initandlisten] git version: 3f76e40c105fc223b3e5aac3e20dcd026b83b38b
2017-02-16T20:40:27.063+0100 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.0.1u-fips  22 Sep 2016
2017-02-16T20:40:27.063+0100 I CONTROL  [initandlisten] allocator: tcmalloc
2017-02-16T20:40:27.063+0100 I CONTROL  [initandlisten] modules: none
2017-02-16T20:40:27.064+0100 I CONTROL  [initandlisten] build environment:
2017-02-16T20:40:27.064+0100 I CONTROL  [initandlisten]     distmod: 2008plus-ssl
2017-02-16T20:40:27.065+0100 I CONTROL  [initandlisten]     distarch: x86_64
2017-02-16T20:40:27.065+0100 I CONTROL  [initandlisten]     target_arch: x86_64
2017-02-16T20:40:27.065+0100 I CONTROL  [initandlisten] options: {}
2017-02-16T20:40:27.066+0100 I STORAGE  [initandlisten] exception in initAndListen: 29 Data directory D:\data\db\ not found., terminating
2017-02-16T20:40:27.066+0100 I NETWORK  [initandlisten] shutdown: going to close listening sockets...
2017-02-16T20:40:27.067+0100 I NETWORK  [initandlisten] shutdown: going to flush diaglog...
2017-02-16T20:40:27.067+0100 I CONTROL  [initandlisten] now exiting
2017-02-16T20:40:27.067+0100 I CONTROL  [initandlisten] shutting down with code:100
```

And running `npm run dev` or `npm start` I get the following error:

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@3.10.10
3 info using node@v6.9.5
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle clash-royale-api@~prestart: clash-royale-api@
6 silly lifecycle clash-royale-api@~prestart: no script for prestart, continuing
7 info lifecycle clash-royale-api@~start: clash-royale-api@
8 verbose lifecycle clash-royale-api@~start: unsafe-perm in lifecycle true
9 verbose lifecycle clash-royale-api@~start: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;D:\Dev\Git\clash-royale-api\node_modules\.bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Git\cmd;C:\php;C:\Program Files\nodejs\;C:\Program Files\MongoDB\Server\3.4\bin;C:\Users\S3BAX\AppData\Local\Programs\Python\Python36-32\Scripts\;C:\Users\S3BAX\AppData\Local\Programs\Python\Python36-32\;C:\Users\S3BAX\AppData\Local\Microsoft\WindowsApps;C:\Users\S3BAX\AppData\Roaming\npm
10 verbose lifecycle clash-royale-api@~start: CWD: D:\Dev\Git\clash-royale-api
11 silly lifecycle clash-royale-api@~start: Args: [ '/d /s /c', 'node server.js' ]
12 silly lifecycle clash-royale-api@~start: Returned: code: 1  signal: null
13 info lifecycle clash-royale-api@~start: Failed to exec start script
14 verbose stack Error: clash-royale-api@ start: `node server.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid clash-royale-api@
16 verbose cwd D:\Dev\Git\clash-royale-api
17 error Windows_NT 10.0.14393
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
19 error node v6.9.5
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error clash-royale-api@ start: `node server.js`
22 error Exit status 1
23 error Failed at the clash-royale-api@ start script 'node server.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the clash-royale-api package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node server.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs clash-royale-api
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls clash-royale-api
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by martincarrera** [comment]
It looks like you don't have a database folder configure for mongo and so it fails to start the database.

There are two things you can try:

1. Create a folder `D:\data\db\`
2. Run the cmd with system privileges.

Please try again and let me know if it's working.

**Comment by TehSebaXx** [comment]
Managed to run Mongo. Npm still gives an error but seems to work:

```
D:\Dev\Git\clash-royale-api>npm start

> clash-royale-api@ start D:\Dev\Git\clash-royale-api
> node server.js

{ Error: ENOENT: no such file or directory, open 'D:\Dev\Git\clash-royale-api\.env'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at Object.config (D:\Dev\Git\clash-royale-api\node_modules\dotenv\lib\main.js:30:37)
    at Object.<anonymous> (D:\Dev\Git\clash-royale-api\src\config\config.js:1:81)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\Dev\Git\clash-royale-api\server.js:2:16)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'D:\\Dev\\Git\\clash-royale-api\\.env' }
(node:7524) DeprecationWarning: Mongoose: mpromise (mongoose's default promise library) is deprecated, plug in your own promise library instead: http://mongoosejs.com/docs/promises.html

```
Going to localhost:8085 I get this: `{"message":"Welcome to Clash Royale API!","endpoints":{"arenas":"api/arenas","cards":"api/cards","chests":"api/chests","players":"api/players"},"version":"1.1.0","lastUpdate":"February 05 2017"}`, but any other endpoint returns just a [].

**Comment by martincarrera** [comment]
Perfect, that means that the API is working.

The error is because you don't have any `.env` file with configuration about the admin username and admin password, to login and create the information. By default it uses `admin` as both username and password.

It is returning `[]` because your database is empty.

If you want to USE the API, you can just consume it from [here](http://www.clashapi.xyz):

- [Arenas](http://www.clashapi.xyz/api/arenas)
- [Cards](http://www.clashapi.xyz/api/cards)
- [Chests](http://www.clashapi.xyz/api/chests)
- [Players](http://www.clashapi.xyz/api/players)

If you want to host it and use your own version, take a look at [this data generator](https://github.com/martincarrera/clash-royale-api-data-generator).

**Comment by TehSebaXx** [comment]
Ok thanks you very much!
